### ISSUE TITLE
GCN and multi-label classification

### ISSUE THREAD

**Issue by MatteoSorge** [THUDM/GraphMAE2#2]
1. I would try to use the gcn for node classification but i noticed that it is not implemented yet in the edcoder.py . I think that you have only to add a few lines of code after the call of gat (also you have to add "from .gcn import GCN")  :
    elif m_type == "gcn":
        mod = GCN(
            in_dim=in_dim,
            num_hidden=num_hidden,
            out_dim=out_dim,
            num_layers=num_layers,
            dropout=dropout,
            activation=activation,
            residual=residual,
            norm=norm,
            encoding=(enc_dec == "encoding"),
            **kwargs,
        )
2. Is possibile to use this framework to do a multi-label classification? Do you have some advice to do it?

**Comment by THINK2TRY** [comment]
@MatteoSorge Thanks for your attention to our work! 
1. Yes, you are right. It is very convenient to add other GNN backbones, such as GCN, as the encoder by just replacing the `model`. We could consider adding other  GNNs later, or you can add one if you need it.
2. Our framework is independent of downstream tasks. To adapt to multi-label classification,  the only thing you have to do is to modify the training of linear probing and change the loss to multi-label criterion. And it would work.

Hope it helps.
