### ISSUE TITLE
在Cora数据集上无法复现出结果

### ISSUE THREAD

**Issue by hcmdgh** [THUDM/GraphMAE2#3]
在Cora数据集上的实验结果为：
--- TestAcc: 0.8230, early-stopping-TestAcc: 0.8240, Best ValAcc: 0.8080 in epoch 222 --- 
final_acc: 0.8230±0.0000
early-stopping_acc: 0.8240±0.0000

试了几次，均无法达到论文中记录的结果：84.5±0.6

**Comment by THINK2TRY** [comment]
@hcmdgh 你好，需要使用提供的脚本`run_fullbatch.sh`开使用提供的最有超参数。以及论文中report的结果是多个 seed 的平均结果。
